#!/bin/bash

echo "🚀 Iniciando todos los servicios para el hackathon..."
echo ""
echo "⚠️  Necesitas 4 terminales abiertas"
echo ""
echo "Terminal 1 - Backend OrigenMX:"
echo "  cd backend && npm run dev"
echo ""
echo "Terminal 2 - Frontend OrigenMX:"
echo "  npm run dev"
echo ""
echo "Terminal 3 - Backend EVVM:"
echo "  cd evvm-mate-fisher/backend && npm run dev"
echo ""
echo "Terminal 4 - Frontend EVVM:"
echo "  cd evvm-mate-fisher/frontend && npm run dev"
echo ""
echo "📱 URLs:"
echo "  • OrigenMX: http://localhost:3000"
echo "  • EVVM: http://localhost:3003"
